FROM openjdk:11.0.9-jre-slim as runtime
MAINTAINER doroshko:eurika_discavery
COPY target/eurika_discavery-0.0.1-SNAPSHOT.jar eurika_discavery-0.0.1-SNAPSHOT.jar
CMD exec java -jar /eurika_discavery-0.0.1-SNAPSHOT.jar
