 version: '3.3'

 services:
  demo2:
    container_name: demo2
    build: ./demo2
    image: demo2
    depends_on:
    - db
    - eurika_discavery
    ports:
    - "8003:8003"
    environment:
      - EUREKA_HOST=http://eurika_discavery:8761/eureka/

  demo3:
    container_name: demo3
    build: ./demo3
    image: demo3
    depends_on:
      - eurika_discavery
    ports:
      - "8004:8004"
    environment:
      - EUREKA_HOST=http://eurika_discavery:8761/eureka/

  eurika_discavery:
    container_name: eurika_discavery
    image: eurika_discavery
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=http://eurika_discavery:8761/eureka/

  db:
    hostname: db
    image: postgres:13.4-alpine
    env_file:
    - database/database.env
    ports:
    - "5433:5432"
    volumes:
    - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    - ./database/db:/var/lib/postgresql/db/