server:
  port: 8004
  servlet:
    context-path: /demodemo
spring:
  application:
    name: demo3
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/tdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: demo3-instance