server:
  port: 8003
  servlet:
    context-path: /demo
spring:
  application:
    name: demo2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/tdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: demo2-instance
