server:
  port: 8003
  servlet:
    context-path: /demo
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
   url: jdbc:postgresql://localhost:5433/tdb
   driver-class-name: org.postgresql.Driver
   username:  postgres
   password:  postgres


